<?php
/**
 * AccountsApi
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform using an omnichannel messaging API. It also allows you to query your account, set up webhooks and buy phone numbers.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Karix\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Karix\ApiException;
use Karix\Configuration;
use Karix\HeaderSelector;
use Karix\ObjectSerializer;

/**
 * AccountsApi Class Doc Comment
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     *
     * @codeCoverageIgnore
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createSubaccount
     *
     * Create a new subaccount
     *
     * @param  \Karix\Model\CreateAccount $subaccount Subaccount object (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Karix\Model\AccountResponse
     */
    public function createSubaccount($subaccount)
    {
        list($response) = $this->createSubaccountWithHttpInfo($subaccount);
        return $response;
    }

    /**
     * Operation createSubaccountWithHttpInfo
     *
     * Create a new subaccount
     *
     * @param  \Karix\Model\CreateAccount $subaccount Subaccount object (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Karix\Model\AccountResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSubaccountWithHttpInfo($subaccount)
    {
        $returnType = '\Karix\Model\AccountResponse';
        $request = $this->createSubaccountRequest($subaccount);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            $this->createSubaccountSetResponseObject($e);
            throw $e;
        }
    }

    /**
     * Operation createSubaccountAsync
     *
     * Create a new subaccount
     *
     * @param  \Karix\Model\CreateAccount $subaccount Subaccount object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSubaccountAsync($subaccount)
    {
        return $this->createSubaccountAsyncWithHttpInfo($subaccount)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSubaccountAsyncWithHttpInfo
     *
     * Create a new subaccount
     *
     * @param  \Karix\Model\CreateAccount $subaccount Subaccount object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSubaccountAsyncWithHttpInfo($subaccount)
    {
        $returnType = '\Karix\Model\AccountResponse';
        $request = $this->createSubaccountRequest($subaccount);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request, $returnType) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        $exception = new ApiException(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                $statusCode,
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $response->getBody()
                        );
                        $this->createSubaccountSetResponseObject($exception);
                        throw $exception;
                    }
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    if ($exception instanceof RequestException) {
                        $response = $exception->getResponse();
                        if ($response) {
                            $statusCode = $response->getStatusCode();
                            $e = new ApiException(
                                sprintf(
                                    '[%d] Error connecting to the API (%s)',
                                    $statusCode,
                                    $exception->getRequest()->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $response->getBody()
                            );
                            $this->createSubaccountSetResponseObject($e);
                            throw $e;
                        }
                        throw new ApiException(
                            "[{$exception->getCode()}] {$exception->getMessage()}",
                            $exception->getCode(),
                            $exception->getResponse() ? $exception->getResponse()->getHeaders() : null,
                            $exception->getResponse() ? $exception->getResponse()->getBody()->getContents() : null
                        );
                    }
                    throw $exception;
                }
            );
    }

    /**
     * Create request for operation 'createSubaccount'
     *
     * @param  \Karix\Model\CreateAccount $subaccount Subaccount object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createSubaccountRequest($subaccount)
    {
        // set constants with only one allowable value
        $api_version = '2.0';
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling createSubaccount'
            );
        }
        // verify the required parameter 'subaccount' is set
        if ($subaccount === null || (is_array($subaccount) && count($subaccount) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subaccount when calling createSubaccount'
            );
        }

        $resourcePath = '/account/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_version !== null) {
            $headerParams['api-version'] = ObjectSerializer::toHeaderValue($api_version);
        }


        // body params
        $_tempBody = null;
        if (isset($subaccount)) {
            $_tempBody = $subaccount;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
    * Sets the response object for an ApiException based on status code
    */
    protected function createSubaccountSetResponseObject($api_exception)
    {
        switch ($api_exception->getCode()) {
            case 201:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\AccountResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 400:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 403:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\UnauthorizedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 500:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
        }
    }

    /**
     * Operation getSubaccount
     *
     * Get a list of accounts
     *
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Karix\Model\AccountListResponse
     */
    public function getSubaccount($offset = '0', $limit = '10')
    {
        list($response) = $this->getSubaccountWithHttpInfo($offset, $limit);
        return $response;
    }

    /**
     * Operation getSubaccountWithHttpInfo
     *
     * Get a list of accounts
     *
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Karix\Model\AccountListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSubaccountWithHttpInfo($offset = '0', $limit = '10')
    {
        $returnType = '\Karix\Model\AccountListResponse';
        $request = $this->getSubaccountRequest($offset, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            $this->getSubaccountSetResponseObject($e);
            throw $e;
        }
    }

    /**
     * Operation getSubaccountAsync
     *
     * Get a list of accounts
     *
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubaccountAsync($offset = '0', $limit = '10')
    {
        return $this->getSubaccountAsyncWithHttpInfo($offset, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSubaccountAsyncWithHttpInfo
     *
     * Get a list of accounts
     *
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubaccountAsyncWithHttpInfo($offset = '0', $limit = '10')
    {
        $returnType = '\Karix\Model\AccountListResponse';
        $request = $this->getSubaccountRequest($offset, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request, $returnType) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        $exception = new ApiException(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                $statusCode,
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $response->getBody()
                        );
                        $this->getSubaccountSetResponseObject($exception);
                        throw $exception;
                    }
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    if ($exception instanceof RequestException) {
                        $response = $exception->getResponse();
                        if ($response) {
                            $statusCode = $response->getStatusCode();
                            $e = new ApiException(
                                sprintf(
                                    '[%d] Error connecting to the API (%s)',
                                    $statusCode,
                                    $exception->getRequest()->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $response->getBody()
                            );
                            $this->getSubaccountSetResponseObject($e);
                            throw $e;
                        }
                        throw new ApiException(
                            "[{$exception->getCode()}] {$exception->getMessage()}",
                            $exception->getCode(),
                            $exception->getResponse() ? $exception->getResponse()->getHeaders() : null,
                            $exception->getResponse() ? $exception->getResponse()->getBody()->getContents() : null
                        );
                    }
                    throw $exception;
                }
            );
    }

    /**
     * Create request for operation 'getSubaccount'
     *
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSubaccountRequest($offset = '0', $limit = '10')
    {
        // set constants with only one allowable value
        $api_version = '2.0';
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling getSubaccount'
            );
        }

        $resourcePath = '/account/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // header params
        if ($api_version !== null) {
            $headerParams['api-version'] = ObjectSerializer::toHeaderValue($api_version);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
    * Sets the response object for an ApiException based on status code
    */
    protected function getSubaccountSetResponseObject($api_exception)
    {
        switch ($api_exception->getCode()) {
            case 200:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\AccountListResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 403:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\UnauthorizedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 500:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
        }
    }

    /**
     * Operation getSubaccountById
     *
     * Get details of an account
     *
     * @param  string $uid Alphanumeric ID of the subaccount to get. (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Karix\Model\AccountResponse
     */
    public function getSubaccountById($uid)
    {
        list($response) = $this->getSubaccountByIdWithHttpInfo($uid);
        return $response;
    }

    /**
     * Operation getSubaccountByIdWithHttpInfo
     *
     * Get details of an account
     *
     * @param  string $uid Alphanumeric ID of the subaccount to get. (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Karix\Model\AccountResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSubaccountByIdWithHttpInfo($uid)
    {
        $returnType = '\Karix\Model\AccountResponse';
        $request = $this->getSubaccountByIdRequest($uid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            $this->getSubaccountByIdSetResponseObject($e);
            throw $e;
        }
    }

    /**
     * Operation getSubaccountByIdAsync
     *
     * Get details of an account
     *
     * @param  string $uid Alphanumeric ID of the subaccount to get. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubaccountByIdAsync($uid)
    {
        return $this->getSubaccountByIdAsyncWithHttpInfo($uid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSubaccountByIdAsyncWithHttpInfo
     *
     * Get details of an account
     *
     * @param  string $uid Alphanumeric ID of the subaccount to get. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubaccountByIdAsyncWithHttpInfo($uid)
    {
        $returnType = '\Karix\Model\AccountResponse';
        $request = $this->getSubaccountByIdRequest($uid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request, $returnType) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        $exception = new ApiException(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                $statusCode,
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $response->getBody()
                        );
                        $this->getSubaccountByIdSetResponseObject($exception);
                        throw $exception;
                    }
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    if ($exception instanceof RequestException) {
                        $response = $exception->getResponse();
                        if ($response) {
                            $statusCode = $response->getStatusCode();
                            $e = new ApiException(
                                sprintf(
                                    '[%d] Error connecting to the API (%s)',
                                    $statusCode,
                                    $exception->getRequest()->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $response->getBody()
                            );
                            $this->getSubaccountByIdSetResponseObject($e);
                            throw $e;
                        }
                        throw new ApiException(
                            "[{$exception->getCode()}] {$exception->getMessage()}",
                            $exception->getCode(),
                            $exception->getResponse() ? $exception->getResponse()->getHeaders() : null,
                            $exception->getResponse() ? $exception->getResponse()->getBody()->getContents() : null
                        );
                    }
                    throw $exception;
                }
            );
    }

    /**
     * Create request for operation 'getSubaccountById'
     *
     * @param  string $uid Alphanumeric ID of the subaccount to get. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSubaccountByIdRequest($uid)
    {
        // set constants with only one allowable value
        $api_version = '2.0';
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling getSubaccountById'
            );
        }
        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling getSubaccountById'
            );
        }

        $resourcePath = '/account/{uid}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_version !== null) {
            $headerParams['api-version'] = ObjectSerializer::toHeaderValue($api_version);
        }

        // path params
        if ($uid !== null) {
            $resourcePath = str_replace(
                '{' . 'uid' . '}',
                ObjectSerializer::toPathValue($uid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
    * Sets the response object for an ApiException based on status code
    */
    protected function getSubaccountByIdSetResponseObject($api_exception)
    {
        switch ($api_exception->getCode()) {
            case 200:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\AccountResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 403:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\UnauthorizedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 404:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\NotFoundResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 500:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
        }
    }

    /**
     * Operation patchSubaccount
     *
     * Edit an account
     *
     * @param  string $uid Alphanumeric ID of the account/subaccount to edit. (required)
     * @param  \Karix\Model\EditAccount $subaccount Subaccount object (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Karix\Model\AccountResponse
     */
    public function patchSubaccount($uid, $subaccount)
    {
        list($response) = $this->patchSubaccountWithHttpInfo($uid, $subaccount);
        return $response;
    }

    /**
     * Operation patchSubaccountWithHttpInfo
     *
     * Edit an account
     *
     * @param  string $uid Alphanumeric ID of the account/subaccount to edit. (required)
     * @param  \Karix\Model\EditAccount $subaccount Subaccount object (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Karix\Model\AccountResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchSubaccountWithHttpInfo($uid, $subaccount)
    {
        $returnType = '\Karix\Model\AccountResponse';
        $request = $this->patchSubaccountRequest($uid, $subaccount);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            $this->patchSubaccountSetResponseObject($e);
            throw $e;
        }
    }

    /**
     * Operation patchSubaccountAsync
     *
     * Edit an account
     *
     * @param  string $uid Alphanumeric ID of the account/subaccount to edit. (required)
     * @param  \Karix\Model\EditAccount $subaccount Subaccount object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchSubaccountAsync($uid, $subaccount)
    {
        return $this->patchSubaccountAsyncWithHttpInfo($uid, $subaccount)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchSubaccountAsyncWithHttpInfo
     *
     * Edit an account
     *
     * @param  string $uid Alphanumeric ID of the account/subaccount to edit. (required)
     * @param  \Karix\Model\EditAccount $subaccount Subaccount object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchSubaccountAsyncWithHttpInfo($uid, $subaccount)
    {
        $returnType = '\Karix\Model\AccountResponse';
        $request = $this->patchSubaccountRequest($uid, $subaccount);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request, $returnType) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        $exception = new ApiException(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                $statusCode,
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $response->getBody()
                        );
                        $this->patchSubaccountSetResponseObject($exception);
                        throw $exception;
                    }
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    if ($exception instanceof RequestException) {
                        $response = $exception->getResponse();
                        if ($response) {
                            $statusCode = $response->getStatusCode();
                            $e = new ApiException(
                                sprintf(
                                    '[%d] Error connecting to the API (%s)',
                                    $statusCode,
                                    $exception->getRequest()->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $response->getBody()
                            );
                            $this->patchSubaccountSetResponseObject($e);
                            throw $e;
                        }
                        throw new ApiException(
                            "[{$exception->getCode()}] {$exception->getMessage()}",
                            $exception->getCode(),
                            $exception->getResponse() ? $exception->getResponse()->getHeaders() : null,
                            $exception->getResponse() ? $exception->getResponse()->getBody()->getContents() : null
                        );
                    }
                    throw $exception;
                }
            );
    }

    /**
     * Create request for operation 'patchSubaccount'
     *
     * @param  string $uid Alphanumeric ID of the account/subaccount to edit. (required)
     * @param  \Karix\Model\EditAccount $subaccount Subaccount object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function patchSubaccountRequest($uid, $subaccount)
    {
        // set constants with only one allowable value
        $api_version = '2.0';
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling patchSubaccount'
            );
        }
        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling patchSubaccount'
            );
        }
        // verify the required parameter 'subaccount' is set
        if ($subaccount === null || (is_array($subaccount) && count($subaccount) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subaccount when calling patchSubaccount'
            );
        }

        $resourcePath = '/account/{uid}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_version !== null) {
            $headerParams['api-version'] = ObjectSerializer::toHeaderValue($api_version);
        }

        // path params
        if ($uid !== null) {
            $resourcePath = str_replace(
                '{' . 'uid' . '}',
                ObjectSerializer::toPathValue($uid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($subaccount)) {
            $_tempBody = $subaccount;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
    * Sets the response object for an ApiException based on status code
    */
    protected function patchSubaccountSetResponseObject($api_exception)
    {
        switch ($api_exception->getCode()) {
            case 200:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\AccountResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 403:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\UnauthorizedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 404:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\NotFoundResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 500:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
        }
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
