<?php
/**
 * MessageApi
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform using an omnichannel messaging API. It also allows you to query your account, set up webhooks and buy phone numbers.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Karix\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Karix\ApiException;
use Karix\Configuration;
use Karix\HeaderSelector;
use Karix\ObjectSerializer;

/**
 * MessageApi Class Doc Comment
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessageApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     *
     * @codeCoverageIgnore
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getMessage
     *
     * Get list of messages sent or received
     *
     * @param  string $direction Message direction, inbound or outbound to filter on. If not provided, the filter is not applied. (optional)
     * @param  string $account_uid Filter the result list by the account which sent the message - If not provided or &#x60;null&#x60; or empty string, no filter will be placed   and all the messages by the main account and its subaccounts are returned - To get the list of messages sent by main account only, set &#x60;account_uid&#x60;   to main account&#39;s uid. (optional)
     * @param  string $state Filter the result on the basis of message state. (optional)
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Karix\Model\MessageListResponse
     */
    public function getMessage($direction = null, $account_uid = null, $state = null, $offset = '0', $limit = '10')
    {
        list($response) = $this->getMessageWithHttpInfo($direction, $account_uid, $state, $offset, $limit);
        return $response;
    }

    /**
     * Operation getMessageWithHttpInfo
     *
     * Get list of messages sent or received
     *
     * @param  string $direction Message direction, inbound or outbound to filter on. If not provided, the filter is not applied. (optional)
     * @param  string $account_uid Filter the result list by the account which sent the message - If not provided or &#x60;null&#x60; or empty string, no filter will be placed   and all the messages by the main account and its subaccounts are returned - To get the list of messages sent by main account only, set &#x60;account_uid&#x60;   to main account&#39;s uid. (optional)
     * @param  string $state Filter the result on the basis of message state. (optional)
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Karix\Model\MessageListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMessageWithHttpInfo($direction = null, $account_uid = null, $state = null, $offset = '0', $limit = '10')
    {
        $returnType = '\Karix\Model\MessageListResponse';
        $request = $this->getMessageRequest($direction, $account_uid, $state, $offset, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            $this->getMessageSetResponseObject($e);
            throw $e;
        }
    }

    /**
     * Operation getMessageAsync
     *
     * Get list of messages sent or received
     *
     * @param  string $direction Message direction, inbound or outbound to filter on. If not provided, the filter is not applied. (optional)
     * @param  string $account_uid Filter the result list by the account which sent the message - If not provided or &#x60;null&#x60; or empty string, no filter will be placed   and all the messages by the main account and its subaccounts are returned - To get the list of messages sent by main account only, set &#x60;account_uid&#x60;   to main account&#39;s uid. (optional)
     * @param  string $state Filter the result on the basis of message state. (optional)
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMessageAsync($direction = null, $account_uid = null, $state = null, $offset = '0', $limit = '10')
    {
        return $this->getMessageAsyncWithHttpInfo($direction, $account_uid, $state, $offset, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMessageAsyncWithHttpInfo
     *
     * Get list of messages sent or received
     *
     * @param  string $direction Message direction, inbound or outbound to filter on. If not provided, the filter is not applied. (optional)
     * @param  string $account_uid Filter the result list by the account which sent the message - If not provided or &#x60;null&#x60; or empty string, no filter will be placed   and all the messages by the main account and its subaccounts are returned - To get the list of messages sent by main account only, set &#x60;account_uid&#x60;   to main account&#39;s uid. (optional)
     * @param  string $state Filter the result on the basis of message state. (optional)
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMessageAsyncWithHttpInfo($direction = null, $account_uid = null, $state = null, $offset = '0', $limit = '10')
    {
        $returnType = '\Karix\Model\MessageListResponse';
        $request = $this->getMessageRequest($direction, $account_uid, $state, $offset, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request, $returnType) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        $exception = new ApiException(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                $statusCode,
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $response->getBody()
                        );
                        $this->getMessageSetResponseObject($exception);
                        throw $exception;
                    }
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    if ($exception instanceof RequestException) {
                        $response = $exception->getResponse();
                        if ($response) {
                            $statusCode = $response->getStatusCode();
                            $e = new ApiException(
                                sprintf(
                                    '[%d] Error connecting to the API (%s)',
                                    $statusCode,
                                    $exception->getRequest()->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $response->getBody()
                            );
                            $this->getMessageSetResponseObject($e);
                            throw $e;
                        }
                        throw new ApiException(
                            "[{$exception->getCode()}] {$exception->getMessage()}",
                            $exception->getCode(),
                            $exception->getResponse() ? $exception->getResponse()->getHeaders() : null,
                            $exception->getResponse() ? $exception->getResponse()->getBody()->getContents() : null
                        );
                    }
                    throw $exception;
                }
            );
    }

    /**
     * Create request for operation 'getMessage'
     *
     * @param  string $direction Message direction, inbound or outbound to filter on. If not provided, the filter is not applied. (optional)
     * @param  string $account_uid Filter the result list by the account which sent the message - If not provided or &#x60;null&#x60; or empty string, no filter will be placed   and all the messages by the main account and its subaccounts are returned - To get the list of messages sent by main account only, set &#x60;account_uid&#x60;   to main account&#39;s uid. (optional)
     * @param  string $state Filter the result on the basis of message state. (optional)
     * @param  int $offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param  int $limit The numbers of items to return. (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMessageRequest($direction = null, $account_uid = null, $state = null, $offset = '0', $limit = '10')
    {
        // set constants with only one allowable value
        $api_version = '2.0';
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling getMessage'
            );
        }

        $resourcePath = '/message/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($direction !== null) {
            $queryParams['direction'] = ObjectSerializer::toQueryValue($direction);
        }
        // query params
        if ($account_uid !== null) {
            $queryParams['account_uid'] = ObjectSerializer::toQueryValue($account_uid);
        }
        // query params
        if ($state !== null) {
            $queryParams['state'] = ObjectSerializer::toQueryValue($state);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // header params
        if ($api_version !== null) {
            $headerParams['api-version'] = ObjectSerializer::toHeaderValue($api_version);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
    * Sets the response object for an ApiException based on status code
    */
    protected function getMessageSetResponseObject($api_exception)
    {
        switch ($api_exception->getCode()) {
            case 200:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\MessageListResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 403:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\UnauthorizedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 500:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
        }
    }

    /**
     * Operation getMessageById
     *
     * Get message details by id.
     *
     * @param  string $uid Alphanumeric ID of the message to get. (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Karix\Model\MessageResponse
     */
    public function getMessageById($uid)
    {
        list($response) = $this->getMessageByIdWithHttpInfo($uid);
        return $response;
    }

    /**
     * Operation getMessageByIdWithHttpInfo
     *
     * Get message details by id.
     *
     * @param  string $uid Alphanumeric ID of the message to get. (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Karix\Model\MessageResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMessageByIdWithHttpInfo($uid)
    {
        $returnType = '\Karix\Model\MessageResponse';
        $request = $this->getMessageByIdRequest($uid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            $this->getMessageByIdSetResponseObject($e);
            throw $e;
        }
    }

    /**
     * Operation getMessageByIdAsync
     *
     * Get message details by id.
     *
     * @param  string $uid Alphanumeric ID of the message to get. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMessageByIdAsync($uid)
    {
        return $this->getMessageByIdAsyncWithHttpInfo($uid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMessageByIdAsyncWithHttpInfo
     *
     * Get message details by id.
     *
     * @param  string $uid Alphanumeric ID of the message to get. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMessageByIdAsyncWithHttpInfo($uid)
    {
        $returnType = '\Karix\Model\MessageResponse';
        $request = $this->getMessageByIdRequest($uid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request, $returnType) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        $exception = new ApiException(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                $statusCode,
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $response->getBody()
                        );
                        $this->getMessageByIdSetResponseObject($exception);
                        throw $exception;
                    }
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    if ($exception instanceof RequestException) {
                        $response = $exception->getResponse();
                        if ($response) {
                            $statusCode = $response->getStatusCode();
                            $e = new ApiException(
                                sprintf(
                                    '[%d] Error connecting to the API (%s)',
                                    $statusCode,
                                    $exception->getRequest()->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $response->getBody()
                            );
                            $this->getMessageByIdSetResponseObject($e);
                            throw $e;
                        }
                        throw new ApiException(
                            "[{$exception->getCode()}] {$exception->getMessage()}",
                            $exception->getCode(),
                            $exception->getResponse() ? $exception->getResponse()->getHeaders() : null,
                            $exception->getResponse() ? $exception->getResponse()->getBody()->getContents() : null
                        );
                    }
                    throw $exception;
                }
            );
    }

    /**
     * Create request for operation 'getMessageById'
     *
     * @param  string $uid Alphanumeric ID of the message to get. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMessageByIdRequest($uid)
    {
        // set constants with only one allowable value
        $api_version = '2.0';
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling getMessageById'
            );
        }
        // verify the required parameter 'uid' is set
        if ($uid === null || (is_array($uid) && count($uid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uid when calling getMessageById'
            );
        }

        $resourcePath = '/message/{uid}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_version !== null) {
            $headerParams['api-version'] = ObjectSerializer::toHeaderValue($api_version);
        }

        // path params
        if ($uid !== null) {
            $resourcePath = str_replace(
                '{' . 'uid' . '}',
                ObjectSerializer::toPathValue($uid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
    * Sets the response object for an ApiException based on status code
    */
    protected function getMessageByIdSetResponseObject($api_exception)
    {
        switch ($api_exception->getCode()) {
            case 200:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\MessageResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 403:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\UnauthorizedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 404:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\NotFoundResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 500:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
        }
    }

    /**
     * Operation sendMessage
     *
     * Send a message to a list of destinations
     *
     * @param  \Karix\Model\CreateMessage $message Create Message object (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Karix\Model\MessageCreatedResponse
     */
    public function sendMessage($message)
    {
        list($response) = $this->sendMessageWithHttpInfo($message);
        return $response;
    }

    /**
     * Operation sendMessageWithHttpInfo
     *
     * Send a message to a list of destinations
     *
     * @param  \Karix\Model\CreateMessage $message Create Message object (required)
     *
     * @throws \Karix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Karix\Model\MessageCreatedResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendMessageWithHttpInfo($message)
    {
        $returnType = '\Karix\Model\MessageCreatedResponse';
        $request = $this->sendMessageRequest($message);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            $this->sendMessageSetResponseObject($e);
            throw $e;
        }
    }

    /**
     * Operation sendMessageAsync
     *
     * Send a message to a list of destinations
     *
     * @param  \Karix\Model\CreateMessage $message Create Message object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMessageAsync($message)
    {
        return $this->sendMessageAsyncWithHttpInfo($message)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendMessageAsyncWithHttpInfo
     *
     * Send a message to a list of destinations
     *
     * @param  \Karix\Model\CreateMessage $message Create Message object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMessageAsyncWithHttpInfo($message)
    {
        $returnType = '\Karix\Model\MessageCreatedResponse';
        $request = $this->sendMessageRequest($message);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request, $returnType) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        $exception = new ApiException(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                $statusCode,
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $response->getBody()
                        );
                        $this->sendMessageSetResponseObject($exception);
                        throw $exception;
                    }
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    if ($exception instanceof RequestException) {
                        $response = $exception->getResponse();
                        if ($response) {
                            $statusCode = $response->getStatusCode();
                            $e = new ApiException(
                                sprintf(
                                    '[%d] Error connecting to the API (%s)',
                                    $statusCode,
                                    $exception->getRequest()->getUri()
                                ),
                                $statusCode,
                                $response->getHeaders(),
                                $response->getBody()
                            );
                            $this->sendMessageSetResponseObject($e);
                            throw $e;
                        }
                        throw new ApiException(
                            "[{$exception->getCode()}] {$exception->getMessage()}",
                            $exception->getCode(),
                            $exception->getResponse() ? $exception->getResponse()->getHeaders() : null,
                            $exception->getResponse() ? $exception->getResponse()->getBody()->getContents() : null
                        );
                    }
                    throw $exception;
                }
            );
    }

    /**
     * Create request for operation 'sendMessage'
     *
     * @param  \Karix\Model\CreateMessage $message Create Message object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendMessageRequest($message)
    {
        // set constants with only one allowable value
        $api_version = '2.0';
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling sendMessage'
            );
        }
        // verify the required parameter 'message' is set
        if ($message === null || (is_array($message) && count($message) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $message when calling sendMessage'
            );
        }

        $resourcePath = '/message/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_version !== null) {
            $headerParams['api-version'] = ObjectSerializer::toHeaderValue($api_version);
        }


        // body params
        $_tempBody = null;
        if (isset($message)) {
            $_tempBody = $message;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
    * Sets the response object for an ApiException based on status code
    */
    protected function sendMessageSetResponseObject($api_exception)
    {
        switch ($api_exception->getCode()) {
            case 202:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\MessageCreatedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 400:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 402:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\InsufficientBalanceResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 403:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\UnauthorizedResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
            case 500:
                $data = ObjectSerializer::deserialize(
                    $api_exception->getResponseBody(),
                    '\Karix\Model\ErrorResponse',
                    $api_exception->getResponseHeaders()
                );
                $api_exception->setResponseObject($data);
                break;
        }
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
