<?php
/**
 * AccountNumberTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform using an omnichannel messaging API. It also allows you to query your account, set up webhooks and buy phone numbers.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Karix;

/**
 * AccountNumberTest Class Doc Comment
 *
 * @category    Class
 * @description AccountNumber
 * @package     Karix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountNumberTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountNumber"
     */
    public function testAccountNumber()
    {
    }

    /**
     * Test attribute "webhook_uid"
     */
    public function testPropertyWebhookUid()
    {
        $account_number = new \Karix\Model\AccountNumber();
        $webhook_uid = "f6bcc10c-09c0-4bd5-9d58-0089fe51c3bb";
        
        $account_number->setWebhookUid($webhook_uid);
        $this->assertEquals($webhook_uid, $account_number->getWebhookUid());

    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
        $account_number = new \Karix\Model\AccountNumber();
        $alias = "Number 1";
        
        $account_number->setAlias($alias);
        $this->assertEquals($alias, $account_number->getAlias());

    }

    /**
     * Test attribute "account_uid"
     */
    public function testPropertyAccountUid()
    {
        $account_number = new \Karix\Model\AccountNumber();
        $account_uid = "8bf925cd-1042-42b2-adc3-de43b64b9b02";
        
        $account_number->setAccountUid($account_uid);
        $this->assertEquals($account_uid, $account_number->getAccountUid());

    }

    /**
     * Test attribute "number_details"
     */
    public function testPropertyNumberDetails()
    {
        $account_number = new \Karix\Model\AccountNumber();
        
        
        $subobj = new \Karix\Model\PhoneNumber();
        

        $number_details = $subobj;
        
        $account_number->setNumberDetails($number_details);
        $this->assertEquals($number_details, $account_number->getNumberDetails());

    }

    /**
     * Test attribute "date_rented"
     */
    public function testPropertyDateRented()
    {
        $account_number = new \Karix\Model\AccountNumber();
        $datetime = \DateTime::createFromFormat(\DateTime::ISO8601, '2017-08-04T09:59:29.660Z');
        $date_rented = $datetime;
        
        $account_number->setDateRented($date_rented);
        $this->assertEquals($date_rented, $account_number->getDateRented());

    }

    /**
    * Helper to create a good example of model
    */
    public function getGoodExample()
    {
        $webhook_uid = "f6bcc10c-09c0-4bd5-9d58-0089fe51c3bb";
        
        $alias = "Number 1";
        
        $account_uid = "8bf925cd-1042-42b2-adc3-de43b64b9b02";
        
        
        
        $subobj = new \Karix\Model\PhoneNumber();
        

        $number_details = $subobj;
        
        $datetime = \DateTime::createFromFormat(\DateTime::ISO8601, '2017-08-04T09:59:29.660Z');
        $date_rented = $datetime;
        
        return array(
            "webhook_uid" => $webhook_uid,
            "alias" => $alias,
            "account_uid" => $account_uid,
            "number_details" => $number_details,
            "date_rented" => $date_rented,
        );
    }

    /**
    * Test AccountNumber validation
    */
    public function testValidation()
    {
        $example = $this->getGoodExample();
        $account_number = new \Karix\Model\AccountNumber($example);
        $this->assertTrue($account_number->valid());
    }

}
