<?php
/**
 * CreateMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform using an omnichannel messaging API. It also allows you to query your account, set up webhooks and buy phone numbers.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Karix;

/**
 * CreateMessageTest Class Doc Comment
 *
 * @category    Class
 * @description CreateMessage
 * @package     Karix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateMessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateMessage"
     */
    public function testCreateMessage()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
        $create_message = new \Karix\Model\CreateMessage();
        $channel = "sms";
        
        $create_message->setChannel($channel);
        $this->assertEquals($channel, $create_message->getChannel());

        // Check for enum
        $create_message->setChannel("sms");
        $create_message->setChannel("whatsapp");
        try
        {
            $create_message->setChannel("Invalid Edwfere");
            $this->fail("$create_message->setChannel accepted input outside of enum");
        }
        catch(\InvalidArgumentException $e){}

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
        $create_message = new \Karix\Model\CreateMessage();
        $source = "+14154009186";
        
        $create_message->setSource($source);
        $this->assertEquals($source, $create_message->getSource());

    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
        $create_message = new \Karix\Model\CreateMessage();
        $create_message_destination = [];
        $subobj = "+15623158625";
        

        $create_message_destination[] = $subobj;
        $destination = $create_message_destination;
        
        $create_message->setDestination($destination);
        $this->assertEquals($destination, $create_message->getDestination());

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
        $create_message = new \Karix\Model\CreateMessage();
        
        
        $subobj = new \Karix\Model\CreateMessageContent();
        

        $content = $subobj;
        
        $create_message->setContent($content);
        $this->assertEquals($content, $create_message->getContent());

    }

    /**
     * Test attribute "events_url"
     */
    public function testPropertyEventsUrl()
    {
        $create_message = new \Karix\Model\CreateMessage();
        $events_url = "https://events.example.com/message";
        
        $create_message->setEventsUrl($events_url);
        $this->assertEquals($events_url, $create_message->getEventsUrl());

    }

    /**
    * Helper to create a good example of model
    */
    public function getGoodExample()
    {
        $channel = "sms";
        
        $source = "+14154009186";
        
        $create_message_destination = [];
        $subobj = "+15623158625";
        

        $create_message_destination[] = $subobj;
        $destination = $create_message_destination;
        
        
        
        $subobj = new \Karix\Model\CreateMessageContent();
        

        $content = $subobj;
        
        $events_url = "https://events.example.com/message";
        
        return array(
            "channel" => $channel,
            "source" => $source,
            "destination" => $destination,
            "content" => $content,
            "events_url" => $events_url,
        );
    }

    /**
    * Test CreateMessage validation
    */
    public function testValidation()
    {
        $example = $this->getGoodExample();
        $create_message = new \Karix\Model\CreateMessage($example);
        $this->assertTrue($create_message->valid());
    }

    /**
    *
    */
    public function testEnumPropertyChannel()
    {
        $example = $this->getGoodExample();
        $example['channel'] = "Invalid Edwfere";
        $create_message = new \Karix\Model\CreateMessage($example);
        $this->assertFalse($create_message->valid());

        $allowedValues = $create_message->getChannelAllowableValues();
        $err_msg = sprintf(
            "invalid value for 'channel', must be one of '%s'",
            implode("', '", $allowedValues)
        );
        $invalidProperties = $create_message->listInvalidProperties();
        $this->assertContains($err_msg, $invalidProperties);
    }

    /**
    *
    */
    public function testRequiredPropertySource()
    {
        $example = $this->getGoodExample();
        $example['source'] = null;
        $create_message = new \Karix\Model\CreateMessage($example);
        $this->assertFalse($create_message->valid());

        $invalidProperties = $create_message->listInvalidProperties();
        $this->assertContains("'source' can't be null", $invalidProperties);
    }

    /**
    *
    */
    public function testRequiredPropertyDestination()
    {
        $example = $this->getGoodExample();
        $example['destination'] = null;
        $create_message = new \Karix\Model\CreateMessage($example);
        $this->assertFalse($create_message->valid());

        $invalidProperties = $create_message->listInvalidProperties();
        $this->assertContains("'destination' can't be null", $invalidProperties);
    }

    /**
    *
    */
    public function testRequiredPropertyContent()
    {
        $example = $this->getGoodExample();
        $example['content'] = null;
        $create_message = new \Karix\Model\CreateMessage($example);
        $this->assertFalse($create_message->valid());

        $invalidProperties = $create_message->listInvalidProperties();
        $this->assertContains("'content' can't be null", $invalidProperties);
    }

}
