<?php
/**
 * CreateMessageContentLocationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform using an omnichannel messaging API. It also allows you to query your account, set up webhooks and buy phone numbers.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Karix;

/**
 * CreateMessageContentLocationTest Class Doc Comment
 *
 * @category    Class
 * @description Location content to be sent to destinations
 * @package     Karix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateMessageContentLocationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateMessageContentLocation"
     */
    public function testCreateMessageContentLocation()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation();
        $longitude = "12.9716";
        
        $create_message_content_location->setLongitude($longitude);
        $this->assertEquals($longitude, $create_message_content_location->getLongitude());

    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation();
        $latitude = "77.5946";
        
        $create_message_content_location->setLatitude($latitude);
        $this->assertEquals($latitude, $create_message_content_location->getLatitude());

    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation();
        $label = "Bangalore";
        
        $create_message_content_location->setLabel($label);
        $this->assertEquals($label, $create_message_content_location->getLabel());

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation();
        $address = "Havoc!";
        
        $create_message_content_location->setAddress($address);
        $this->assertEquals($address, $create_message_content_location->getAddress());

    }

    /**
    * Helper to create a good example of model
    */
    public function getGoodExample()
    {
        $longitude = "12.9716";
        
        $latitude = "77.5946";
        
        $label = "Bangalore";
        
        $address = "Havoc!";
        
        return array(
            "longitude" => $longitude,
            "latitude" => $latitude,
            "label" => $label,
            "address" => $address,
        );
    }

    /**
    * Test CreateMessageContentLocation validation
    */
    public function testValidation()
    {
        $example = $this->getGoodExample();
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation($example);
        $this->assertTrue($create_message_content_location->valid());
    }

    /**
    *
    */
    public function testRequiredPropertyLongitude()
    {
        $example = $this->getGoodExample();
        $example['longitude'] = null;
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation($example);
        $this->assertFalse($create_message_content_location->valid());

        $invalidProperties = $create_message_content_location->listInvalidProperties();
        $this->assertContains("'longitude' can't be null", $invalidProperties);
    }

    /**
    *
    */
    public function testRequiredPropertyLatitude()
    {
        $example = $this->getGoodExample();
        $example['latitude'] = null;
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation($example);
        $this->assertFalse($create_message_content_location->valid());

        $invalidProperties = $create_message_content_location->listInvalidProperties();
        $this->assertContains("'latitude' can't be null", $invalidProperties);
    }

    /**
    *
    */
    public function testRequiredPropertyLabel()
    {
        $example = $this->getGoodExample();
        $example['label'] = null;
        $create_message_content_location = new \Karix\Model\CreateMessageContentLocation($example);
        $this->assertFalse($create_message_content_location->valid());

        $invalidProperties = $create_message_content_location->listInvalidProperties();
        $this->assertContains("'label' can't be null", $invalidProperties);
    }

}
