<?php
/**
 * EditWebhookTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform. It allows you to query your account, set up webhooks, send messages and buy phone numbers.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Karix;

/**
 * EditWebhookTest Class Doc Comment
 *
 * @category    Class
 * @description EditWebhook
 * @package     Karix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EditWebhookTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EditWebhook"
     */
    public function testEditWebhook()
    {
    }

    /**
     * Test attribute "sms_notification_url"
     */
    public function testPropertySmsNotificationUrl()
    {
        $edit_webhook = new \Karix\Model\EditWebhook();
        $sms_notification_url = "https://notification.example.com/sms";
        
        $edit_webhook->setSmsNotificationUrl($sms_notification_url);
        $this->assertEquals($sms_notification_url, $edit_webhook->getSmsNotificationUrl());

    }

    /**
     * Test attribute "sms_notification_method"
     */
    public function testPropertySmsNotificationMethod()
    {
        $edit_webhook = new \Karix\Model\EditWebhook();
        $sms_notification_method = "POST";
        
        $edit_webhook->setSmsNotificationMethod($sms_notification_method);
        $this->assertEquals($sms_notification_method, $edit_webhook->getSmsNotificationMethod());

    }

    /**
     * Test attribute "sms_notification_fallback_url"
     */
    public function testPropertySmsNotificationFallbackUrl()
    {
        $edit_webhook = new \Karix\Model\EditWebhook();
        $sms_notification_fallback_url = "https://notification.example.com/sms";
        
        $edit_webhook->setSmsNotificationFallbackUrl($sms_notification_fallback_url);
        $this->assertEquals($sms_notification_fallback_url, $edit_webhook->getSmsNotificationFallbackUrl());

    }

    /**
     * Test attribute "sms_notification_fallback_method"
     */
    public function testPropertySmsNotificationFallbackMethod()
    {
        $edit_webhook = new \Karix\Model\EditWebhook();
        $sms_notification_fallback_method = "POST";
        
        $edit_webhook->setSmsNotificationFallbackMethod($sms_notification_fallback_method);
        $this->assertEquals($sms_notification_fallback_method, $edit_webhook->getSmsNotificationFallbackMethod());

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $edit_webhook = new \Karix\Model\EditWebhook();
        $name = "webhook_1";
        
        $edit_webhook->setName($name);
        $this->assertEquals($name, $edit_webhook->getName());

    }

    /**
    * Helper to create a good example of model
    */
    public function getGoodExample()
    {
        $sms_notification_url = "https://notification.example.com/sms";
        
        $sms_notification_method = "POST";
        
        $sms_notification_fallback_url = "https://notification.example.com/sms";
        
        $sms_notification_fallback_method = "POST";
        
        $name = "webhook_1";
        
        return array(
            "sms_notification_url" => $sms_notification_url,
            "sms_notification_method" => $sms_notification_method,
            "sms_notification_fallback_url" => $sms_notification_fallback_url,
            "sms_notification_fallback_method" => $sms_notification_fallback_method,
            "name" => $name,
        );
    }

    /**
    * Test EditWebhook validation
    */
    public function testValidation()
    {
        $example = $this->getGoodExample();
        $edit_webhook = new \Karix\Model\EditWebhook($example);
        $this->assertTrue($edit_webhook->valid());
    }

}
