<?php
/**
 * MessageContentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform using an omnichannel messaging API. It also allows you to query your account, set up webhooks and buy phone numbers.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Karix;

/**
 * MessageContentTest Class Doc Comment
 *
 * @category    Class
 * @description Content to be sent to the destinations. - For channel &#x60;sms&#x60; only &#x60;text&#x60; content is supported - Only one of &#x60;text&#x60; or &#x60;location&#x60; can be provided
 * @package     Karix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageContentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MessageContent"
     */
    public function testMessageContent()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
        $message_content = new \Karix\Model\MessageContent();
        $text = "Hey, Rick. It's Rick.";
        
        $message_content->setText($text);
        $this->assertEquals($text, $message_content->getText());

    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
        $message_content = new \Karix\Model\MessageContent();
        
        
        $subobj = new \Karix\Model\MessageContentLocation();
        

        $location = $subobj;
        
        $message_content->setLocation($location);
        $this->assertEquals($location, $message_content->getLocation());

    }

    /**
    * Helper to create a good example of model
    */
    public function getGoodExample()
    {
        $text = "Hey, Rick. It's Rick.";
        
        
        
        $subobj = new \Karix\Model\MessageContentLocation();
        

        $location = $subobj;
        
        return array(
            "text" => $text,
            "location" => $location,
        );
    }

    /**
    * Test MessageContent validation
    */
    public function testValidation()
    {
        $example = $this->getGoodExample();
        $message_content = new \Karix\Model\MessageContent($example);
        $this->assertTrue($message_content->valid());
    }

}
