<?php
/**
 * NotFoundResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform using an omnichannel messaging API. It also allows you to query your account, set up webhooks and buy phone numbers.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Karix;

/**
 * NotFoundResponseTest Class Doc Comment
 *
 * @category    Class
 * @description NotFoundResponse
 * @package     Karix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotFoundResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NotFoundResponse"
     */
    public function testNotFoundResponse()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
        $not_found_response = new \Karix\Model\NotFoundResponse();
        
        
        $subobj = new \Karix\Model\MetaResponse();
        

        $meta = $subobj;
        
        $not_found_response->setMeta($meta);
        $this->assertEquals($meta, $not_found_response->getMeta());

    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
        $not_found_response = new \Karix\Model\NotFoundResponse();
        
        
        $subobj = new \Karix\Model\NotFoundResponseError();
        

        $error = $subobj;
        
        $not_found_response->setError($error);
        $this->assertEquals($error, $not_found_response->getError());

    }

    /**
    * Helper to create a good example of model
    */
    public function getGoodExample()
    {
        
        
        $subobj = new \Karix\Model\MetaResponse();
        

        $meta = $subobj;
        
        
        
        $subobj = new \Karix\Model\NotFoundResponseError();
        

        $error = $subobj;
        
        return array(
            "meta" => $meta,
            "error" => $error,
        );
    }

    /**
    * Test NotFoundResponse validation
    */
    public function testValidation()
    {
        $example = $this->getGoodExample();
        $not_found_response = new \Karix\Model\NotFoundResponse($example);
        $this->assertTrue($not_found_response->valid());
    }

}
