<?php
/**
 * NumberRentedResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform. It allows you to query your account, set up webhooks, send messages and buy phone numbers.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Karix;

/**
 * NumberRentedResponseTest Class Doc Comment
 *
 * @category    Class
 * @description NumberRentedResponse
 * @package     Karix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NumberRentedResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NumberRentedResponse"
     */
    public function testNumberRentedResponse()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
        $number_rented_response = new \Karix\Model\NumberRentedResponse();
        
        
        $subobj = new \Karix\Model\MetaResponseWithBalance();
        

        $meta = $subobj;
        
        $number_rented_response->setMeta($meta);
        $this->assertEquals($meta, $number_rented_response->getMeta());

    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        $number_rented_response = new \Karix\Model\NumberRentedResponse();
        
        
        $subobj = new \Karix\Model\AccountNumber();
        

        $data = $subobj;
        
        $number_rented_response->setData($data);
        $this->assertEquals($data, $number_rented_response->getData());

    }

    /**
    * Helper to create a good example of model
    */
    public function getGoodExample()
    {
        
        
        $subobj = new \Karix\Model\MetaResponseWithBalance();
        

        $meta = $subobj;
        
        
        
        $subobj = new \Karix\Model\AccountNumber();
        

        $data = $subobj;
        
        return array(
            "meta" => $meta,
            "data" => $data,
        );
    }

    /**
    * Test NumberRentedResponse validation
    */
    public function testValidation()
    {
        $example = $this->getGoodExample();
        $number_rented_response = new \Karix\Model\NumberRentedResponse($example);
        $this->assertTrue($number_rented_response->valid());
    }

}
