<?php
/**
 * NumberApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * karix api
 *
 * Karix API lets you interact with the Karix platform. It allows you to query your account, set up webhooks, send messages and buy phone numbers.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@karix.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Karix;

use \Karix\Configuration;
use \Karix\ApiException;
use \Karix\ObjectSerializer;

/**
 * NumberApiTest Class Doc Comment
 *
 * @category Class
 * @package  Karix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NumberApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getNumber
     *
     * Get details of all phone numbers linked to your account..
     *
     */
    public function testGetNumber()
    {
    }

    /**
     * Test case for numberNumDelete
     *
     * Unrent number from your account.
     *
     */
    public function testNumberNumDelete()
    {
    }

    /**
     * Test case for numberNumGet
     *
     * Get details of a number.
     *
     */
    public function testNumberNumGet()
    {
    }

    /**
     * Test case for numberNumPatch
     *
     * Edit phone number belonging to your account.
     *
     */
    public function testNumberNumPatch()
    {
    }

    /**
     * Test case for rentNumber
     *
     * Rent a phone number.
     *
     */
    public function testRentNumber()
    {
    }
}
